# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Header Configuration
avatar = "https://media.licdn.com/dms/image/v2/D5603AQHGV8MuXUJMHg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1730713151537?e=1762992000&v=beta&t=youpwuU4_NWj0p0VxrhSxhZdQ0-ITc7QtgCKC7bKIxE"

#favicon
favicon = "icons/favicon-32x32.png"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true